# SPDX-FileCopyrightText: 2024 László Vaskó <vlaci@fastmail.com>
#
# SPDX-License-Identifier: EUPL-1.2

version = 1

[[annotations]]
path = "**/input"
  
SPDX-FileCopyrightText = "2024 Eric Wastl"
SPDX-License-Identifier = "CC0-1.0"
