# SPDX-FileCopyrightText: 2024 László Vaskó <vlaci@fastmail.com>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
name = "day03"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
peg = "0.8.4"

[dev-dependencies]
rstest = "0.23.0"
